// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sptcbtbakguqfnmbepqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwdGNidGJha2d1cWZubWJlcHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTg4NTgsImV4cCI6MjA3MDE3NDg1OH0.2uSEmyU8yjAn8EqYi_b61jxN2WkAYVl_rUsAUYmOFHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});